# Generated by Django 4.1.1 on 2022-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eshop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_address', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('prodcut_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='ProductPhotos/')),
                ('product_price', models.BigIntegerField()),
            ],
        ),
    ]
