# Generated by Django 4.1.1 on 2022-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eshop',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
